apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notebook-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: opendatahub
  name: notebook-controller
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: notebook-controller
status:
  loadBalancer: {}
