apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve
    app.kubernetes.io/part-of: opendatahub
  name: kserver4am
spec:
  port:
    targetPort: 8443
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: kserve
    weight: 100
status: {}
