apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: baseubi8-python-38-notebooks-grql
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: baseubi8-python-38-notebooks-grql
    app.kubernetes.io/part-of: opendatahub
  name: baseubi8-python-38-notebooks-grql
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app.kubernetes.io/instance: baseubi8-python-38-notebooks-grql
status:
  loadBalancer: {}
