apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: opendatahub-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opendatahub-operator
    app.kubernetes.io/part-of: opendatahub
  name: opendatahub-operator
spec:
  ports:
  - port: 125
    targetPort: 125
  selector:
    app.kubernetes.io/instance: opendatahub-operator
status:
  loadBalancer: {}
