apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nb-base-ubi9-python-3-9
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nb-base-ubi9-python-3-9
    app.kubernetes.io/part-of: opendatahub
  name: nb-base-ubi9-python-3-93uoe
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nb-base-ubi9-python-3-9
    weight: 100
status: {}
