apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: trustyai-service-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trustyai-service-operator
    app.kubernetes.io/part-of: opendatahub
  name: trustyai-service-operator
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: trustyai-service-operator
status:
  loadBalancer: {}
