apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: notebook-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: notebook-controller
    app.kubernetes.io/part-of: opendatahub
  name: notebook-controllerabkv
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: notebook-controller
    weight: null
status: {}
