apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: text-generation-inference
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: text-generation-inference
    app.kubernetes.io/part-of: opendatahub
  name: text-generation-inference
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: text-generation-inference
status:
  loadBalancer: {}
