apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: opendatahub-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opendatahub-operator
    app.kubernetes.io/part-of: opendatahub
  name: opendatahub-operator53ty
spec:
  port:
    targetPort: 125
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: opendatahub-operator
    weight: 100
status: {}
