apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: data-science-pipelines-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: data-science-pipelines-operator
    app.kubernetes.io/part-of: opendatahub
  name: data-science-pipelines-operator
spec:
  ports:
  - port: 8089
    targetPort: 8089
  selector:
    app.kubernetes.io/instance: data-science-pipelines-operator
status:
  loadBalancer: {}
