apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve
    app.kubernetes.io/part-of: opendatahub
  name: kserve
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/opendatahub/kserve@sha256:db8fdae311cb25875c71626503b27a7670e068d217cc0da4e331bea25516a5e3
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8443
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
