apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve
    app.kubernetes.io/part-of: opendatahub
  name: kserve
spec:
  ports:
  - port: 8443
    targetPort: 8443
  selector:
    app.kubernetes.io/instance: kserve
status:
  loadBalancer: {}
