apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nb-base-ubi9-python-3-9
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nb-base-ubi9-python-3-9
    app.kubernetes.io/part-of: opendatahub
  name: nb-base-ubi9-python-3-9
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nb-base-ubi9-python-3-9
status:
  loadBalancer: {}
