apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trustyai-explainability-7ffg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/opendatahub/trustyai-explainability-7ffg@sha256:9b3ad7542a187de2eab12331503421ef1f418ba901e5c047d4c4bcb13f43cfce
        name: container-image
        resources: {}
status: {}
