apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trustyai-explainability-7ffg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/opendatahub/trustyai-explainability-7ffg@sha256:c49fa01ca7952f02a8c869bcb07269bd3e836ad1705561e195a5450ae19dcafe
        name: container-image
        resources: {}
status: {}
